// <auto-generated />


#nullable disable

using System;
using AmeServer.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
namespace AmeServer.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220228212747_AddressPool")]
    partial class AddressPool
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AmeServer.Core.Entities.NetworkConfiguration", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Dhcp")
                        .IsRequired()
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Dns")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gateways")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoolMax")
                        .IsRequired()
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("PoolMin")
                        .IsRequired()
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("SubnetMask")
                        .IsRequired()
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NetworkConfigurations");
                });

            modelBuilder.Entity("AmeServer.Core.Entities.NetworkDevice", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ClientAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("LeaseTimeSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("Permanent")
                        .HasColumnType("bit");

                    b.Property<string>("PreferredNetworkConfiguration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresentedName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NetworkDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
